// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDwuf4ASxGVHQDpJYG8Nba2NhMXlLXHvk0",
      appId: "1:35723641214:android:30a76da5798922bf5b332f",
      messagingSenderId: "35723641214",
      projectId: "star-kids-c24da",
    authDomain: 'secondserving-ef1f1.firebaseapp.com',
    databaseURL: 'https://star-kids-c24da-default-rtdb.firebaseio.com',
    storageBucket: 'star-kids-c24da.appspot.com',
    measurementId: 'G-SCP8GWL34D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDwuf4ASxGVHQDpJYG8Nba2NhMXlLXHvk0",
      appId: "1:35723641214:android:30a76da5798922bf5b332f",
      messagingSenderId: "35723641214",
      projectId: "star-kids-c24da",
    databaseURL: 'https://star-kids-c24da-default-rtdb.firebaseio.com',
    storageBucket: 'star-kids-c24da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDwuf4ASxGVHQDpJYG8Nba2NhMXlLXHvk0",
      appId: "1:35723641214:android:30a76da5798922bf5b332f",
      messagingSenderId: "35723641214",
      projectId: "star-kids-c24da",
    databaseURL: 'https://star-kids-c24da-default-rtdb.firebaseio.com',
    storageBucket: 'star-kids-c24da.appspot.com',
    iosClientId: '566371582218-b2gqrmsr77sg55t16gkn22eq10knmkej.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondserving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyDwuf4ASxGVHQDpJYG8Nba2NhMXlLXHvk0",
      appId: "1:35723641214:android:30a76da5798922bf5b332f",
      messagingSenderId: "35723641214",
      projectId: "star-kids-c24da",
    databaseURL: 'https://star-kids-c24da-default-rtdb.firebaseio.com',
    storageBucket: 'star-kids-c24da.appspot.com',
    iosClientId: '566371582218-b2gqrmsr77sg55t16gkn22eq10knmkej.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondserving',
  );
}