// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwuf4ASxGVHQDpJYG8Nba2NhMXlLXHvk0',
    appId: '1:35723641214:web:97c2b6a4bb92f95e5b332f',
    messagingSenderId: '35723641214',
    projectId: 'star-kids-c24da',
    authDomain: 'star-kids-c24da.firebaseapp.com',
    databaseURL: 'https://star-kids-c24da-default-rtdb.firebaseio.com',
    storageBucket: 'star-kids-c24da.appspot.com',
    measurementId: 'G-G56CQ5J41Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2khN1TVcF8OxpOZZyTQjw9rjjP_1Q6pY',
    appId: '1:35723641214:android:a6cae971c9822a6d5b332f',
    messagingSenderId: '35723641214',
    projectId: 'star-kids-c24da',
    databaseURL: 'https://star-kids-c24da-default-rtdb.firebaseio.com',
    storageBucket: 'star-kids-c24da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaUUt5-aD9QAv18A3g8kKt9WVUT5BA7KM',
    appId: '1:35723641214:ios:49ab43163b6c46e35b332f',
    messagingSenderId: '35723641214',
    projectId: 'star-kids-c24da',
    databaseURL: 'https://star-kids-c24da-default-rtdb.firebaseio.com',
    storageBucket: 'star-kids-c24da.appspot.com',
    androidClientId: '35723641214-uqn5bcp0c85tltokahpt6es2k674756s.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaUUt5-aD9QAv18A3g8kKt9WVUT5BA7KM',
    appId: '1:35723641214:ios:dde0f12927a565955b332f',
    messagingSenderId: '35723641214',
    projectId: 'star-kids-c24da',
    databaseURL: 'https://star-kids-c24da-default-rtdb.firebaseio.com',
    storageBucket: 'star-kids-c24da.appspot.com',
    androidClientId: '35723641214-uqn5bcp0c85tltokahpt6es2k674756s.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterProject.RunnerTests',
  );
}
